.\"
.\" Copyright (c) 2016 Kyle Milz <kyle@0x30.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 9 2016 $
.Dt CITRUN-GL 1
.Os
.Sh NAME
.Nm citrun_gl
.Nd OpenGL viewer
.Sh DESCRIPTION
Multiplexes execution data from any running instrumented programs into an
OpenGL window.
.Pp
Started instrumented programs will try connecting to
.Nm
when it is running. When that succeeds execution data will appear in the viewer
window.
.Pp
.Nm
uses process group information from connected programs to aggregate similar
processes together.
.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/citrun.socket
Listen socket.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr citrun_wrap 1 ,
.Xr citrun_term 1
