.Dd April 1, 2016
.Dt CITRUN-INST 1
.Os
.Sh NAME
.Nm citrun-inst
.Nd instrument source code
.Sh DESCRIPTION
Warning:
.Nm
is not meant to be invoked directly. Instead, it is invoked automatically from
.Xr citrun-wrap 1 .
.Pp
Instrumentation is attempted on any C or C++ source files found on the command
line. Source files are matched on suffix, one of:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It .c
.It .cc
.It .cpp
.It .cxx
.El
.Pp
When instrumentation is successful modified source files are compiled with
the native command line.
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev CITRUN_PATH
Directory of symlinks named after supported compiler binaries.
.It Ev PATH
Must contain
.Ev CITRUN_PATH .
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr citrun-gl 1 ,
.Xr citrun-wrap 1
