.\"
.\" Copyright (c) 2016 Kyle Milz <kyle@0x30.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 1 2016 $
.Dt CITRUN-INST 1
.Os
.Sh NAME
.Nm citrun-inst
.Nd source to source transformation
.Sh DESCRIPTION
.Nm
modifies source files found on its command line.
It is usually called from
.Xr citrun-wrap 1 .
.Pp
Command line source files are matched on suffix, one of:
.Pp
.Bl -tag -offset indent -compact
.It .c
.It .cc
.It .cpp
.It .cxx
.El
.Pp
When
.Nm
is called directly it attempts instrumentation on any source files found on its
command line.
.Pp
When
.Nm
is called from a build command searching
.Ev PATH
for compiler executables it attempts instrumentation on any source files found
on its command line and then executes that command line with modified files in
place.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr citrun-gl 1 ,
.Xr citrun-wrap 1
