#!/bin/sh

scv_root=/home/kyle/src/scv

if ! test -d $scv_root/instrument/compilers; then
	echo error: compilers/ directory does not exist
	exit 1
fi

export SCV_PATH="$scv_root/instrument/compilers"
export PATH="$SCV_PATH:$PATH"

export CFLAGS="-I$scv_root/lib"
export LDFLAGS="-L$scv_root/lib"

export LDADD="-lscv"

# Used for running programs
export LD_LIBRARY_PATH="$scv_root/lib"
export DYLD_LIBRARY_PATH="$scv_root/lib"

exec $@
