.\"
.\" Copyright (c) 2016 Kyle Milz <kyle@0x30.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: August 3 2016 $
.Dt CITRUN_CHECK 1
.Os
.Sh NAME
.Nm citrun_check
.Nd check for rewrite activity
.Sh SYNOPSIS
.Nm
.Op Ar dir
.Sh DESCRIPTION
The
.Nm
utility searches for activity logs created by
.Xr citrun_wrap 1 .
If
.Ar dir
is given it will be searched instead of the current working
directory.
.Pp
The
.Nm
utility will usually output two sections titled
.Qq Summary
and
.Qq Totals
each containing counts of certain events that occurred during
rewriting.
.Pp
The
.Qq Summary
section contains at least one of the following events:
.Pp
.Bl -tag -width Ds
.It Source files used as input
The total number of C/C++ source files input for rewriting.
.It Application link commands
The number of application link commands detected during rewriting.
.It Successful modified source compiles
The number of rewritten source files successfully compiled with the native
compiler.
.It Failed modified source compiles
The number of rewritten source files that failed compilation with the native
compiler.
.Pp
This can happen for either two reasons:
.Bl -bullet -compact
.It
Compiling the original source file would have failed too
.It
Only compiling the rewritten source file failed
.El
.Pp
The current software design does not admit an efficient, automatic method to
tell the above two cases apart.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr citrun_wrap 1
