.\"
.\" Copyright (c) 2016 Kyle Milz <kyle@0x30.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 10 2016 $
.Dt CITRUN_WRAP 1
.Os
.Sh NAME
.Nm citrun_wrap
.Nd enable C It Run on a build command
.Sh SYNOPSIS
.Nm
.Ar build_cmd
.Op Ar ...
.Sh DESCRIPTION
Special information must be added to a programs source code in order to see it
run.
.Pp
The
.Nm
utility enables source code rewriting on any files compiled during
.Ar build_cmd .
Ideally
.Ar build_cmd
is the top level build command.
.Pp
The given
.Ar build_cmd
must search
.Ev PATH
when finding compiler binaries that must be one of the following:
.Pp
.Bl -bullet -compact
.It
c++
.It
cc
.It
clang
.It
clang++
.It
eg++
.It
egcc
.It
g++
.It
gcc
.El
.Pp
All rewriting activity is written to
.Pa citrun.log
files and human readable summaries can be generated from them with
.Xr citrun_check 1 .
.Pp
Incremental building is supported by
.Nm
but mixing object files created by different
versions of C It Run is not.
.Sh FILES
.Bl -tag -width Ds
.It Pa citrun.log
Rewrite activity log.
.El
.Sh EXIT STATUS
The
.Nm
utility exits with the build command exit code.
.Sh EXAMPLES
Let
.Qq program
be in a project that is:
.Pp
.Bl -bullet -compact
.It
written in C
.It
compiled with gcc
.It
built with make and make searches PATH for gcc
.El
.Pp
Prepending
.Nm
to the build command adds instrumentation:
.Pp
.Dl $ citrun_wrap make
.Pp
Now see
.Qq program
run:
.Pp
.Dl $ ./program
.Pp
If no viewer is running then
.Xr citrun_gl 1
is started.
.Sh SEE ALSO
.Xr citrun_check 1 ,
.Xr citrun_gl 1
