Document: citrun
Title: Debian citrun Manual
Author: <insert document author here>
Abstract: This manual describes what citrun is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/citrun/citrun.sgml.gz

Format: postscript
Files: /usr/share/doc/citrun/citrun.ps.gz

Format: text
Files: /usr/share/doc/citrun/citrun.text.gz

Format: HTML
Index: /usr/share/doc/citrun/html/index.html
Files: /usr/share/doc/citrun/html/*.html
