LIB= glyphy
SRCS= glyphy-arc.cxx glyphy-arcs.cxx glyphy-blob.cxx glyphy-extents.cxx 
SRCS += glyphy-outline.cxx glyphy-sdf.cxx glyphy-shaders.cxx

CXXFLAGS += -I. -DPKGDATADIR=""
LDADD += -lstdc++

NOPROFILE=1
NO_PROFILE=1
.include <bsd.lib.mk>
