strip_preamble()
{
	file="${1}"
	tail -n +33 $file.citrun > $file.citrun_nohdr
}

strip_log()
{
	sed	-e "s,^.*: ,,"	\
		-e "s,'.*','',"	\
		-e "s,(.*),()," \
		-e "/Milliseconds/d" \
		< ${1} > ${1}.stripped
}

strip_millis()
{
	ok "stripping milliseconds" sed -i -e "/Milliseconds spent/d" $1
}

modify_PATH()
{
	export PATH="`pwd`/src:${PATH}"
}

enter_tmpdir()
{
	tmpdir=`mktemp -d /tmp/citrun.XXXXXXXXXX`
	cd $tmpdir
}
