. t/libtap.subr

export PATH="`pwd`/src:${PATH}"
export CITRUN_PROCDIR="procdir/"

treedir=`pwd`

tmpdir=`mktemp -d /tmp/citrun.XXXXXXXXXX` || exit 1
cd $tmpdir

strip_preamble()
{
	file="${1}"
	tail -n +39 $file.citrun > $file.citrun_nohdr
}

strip_log()
{
	sed	-e "s,^.*: ,,"	\
		-e "s,'.*','',"	\
		-e "s,(.*),()," \
		-e "/Milliseconds/d" \
		< ${1} > ${1}.stripped
}

strip_millis()
{
	ok "are milliseconds sanitized" sed -i -e "/Milliseconds spent/d" $1
}
