.Dd April 1, 2016
.Dt CITRUN-INST 1
.Os
.Sh NAME
.Nm citrun-inst
.Nd instrument source code
.Sh DESCRIPTION
Warning:
.Nm
is not meant to be invoked directly. Instead, it is called automatically from
.Xr citrun-wrap 1 .
.Pp
Instrumentation will be attempted on any C/C++ source files found on the command
line. Source files are matched on suffix, one of:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It .c
.It .cc
.It .cpp
.It .cxx
.El
.Pp
When instrumentation is successful modified source files are compiled with
the native command line.
.Pp
When application link commands are detected extra arguments are added to the
command line for the runtime library libcitrun.
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev CITRUN_PATH
Directory of symlinks named after supported compiler binaries.
.It Ev PATH
Must contain
.Ev CITRUN_PATH .
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa INSTRUMENTED
File containing the names of all instrumented object files.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr citrun-gl 1 ,
.Xr citrun-wrap 1
