.Dd April 1, 2016
.Dt CITRUN-INST 1
.Os
.Sh NAME
.Nm citrun-inst
.Nd modify command line and instrument source
.Sh DESCRIPTION
.Nm
will not function correctly when invoked directly.
.Pp
Instead
.Nm
is called from compiler named symlinks put on the
PATH by
.Xr citrun-wrap 1 .
This makes adding instrumentation transparent to the native build system with no
special modifications necessary.
.Pp
Instrumentation will be attempted on any arguments found on the command line
that have one of the following suffixes:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It .c
.It .cc
.It .cpp
.It .cxx
.El
.Pp
When instrumentation is successful original source file paths are replaced with
instrumented ones. Finally the real compiler is called.
.Pp
When application link commands are detected flags for the citrun runtime are
automatically added.
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev CITRUN_PATH
Location where compiler named symlinks are installed.
.It Ev PATH
Must contain
.Ev CITRUN_PATH .
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa LAST_NODE
Last instrumented symbol name. Must be deleted after successfully linking an
instrumented application.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr citrun-gl 1 ,
.Xr citrun-wrap 1
