.Dd April 9, 2016
.Dt CITRUN-GL 1
.Os
.Sh NAME
.Nm citrun-gl
.Nd watch instrumented binaries run
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
Displays executing source code from any instrumented binaries running on the
system.
.Pp
Instrumented binaries built with
.Xr citrun-wrap 1
automatically attempt connections to the
.Nm
socket.
.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/citrun-gl.socket
Default listening socket.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr citrun-wrap 1
