.Dd April 1, 2016
.Dt CITRUN_INSTRUMENT 1
.Os
.Sh NAME
.Nm citrun_instrument
.Nd instrument source code
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is not meant to be invoked directly. Rather it is meant to be called from
compiler named symlinks that are put on the $PATH by
.Xr citrun_wrap 1 .
.Pp
If
.Xr citrun_gl 1
is running any applications instrumented by this utility will try connecting to it.
.Sh SEE ALSO
.Xr citrun_gl 1 ,
.Xr citrun_wrap 1
