.Dd March 13, 2016
.Dt CITRUN_GL 1
.Os
.Sh NAME
.Nm citrun_gl
.Nd see it run
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
Displays executing source code from any instrumented binaries running on the
system.
.Pp
Instrumented binaries are typically built by wrapping an applications native
build command with
.Xr citrun_wrap 1 .
.Sh SEE ALSO
.Xr citrun_wrap 1
