LIB = glyphy

SRCS += glyphy-arc.cc \
	glyphy-arcs.cc \
	glyphy-blob.cc \
	glyphy-extents.cc \
	glyphy-outline.cc \
	glyphy-sdf.cc \
	glyphy-shaders.cc

CXXFLAGS += -I. -DPKGDATADIR=""

NOPROFILE=1
NO_PROFILE=1
.include <bsd.lib.mk>
