LIB = glyphy

SRCS += glyphy-arc.cxx \
	glyphy-arcs.cxx \
	glyphy-blob.cxx \
	glyphy-extents.cxx \
	glyphy-outline.cxx \
	glyphy-sdf.cxx \
	glyphy-shaders.cxx

CXXFLAGS += -std=c++11 -I. -DPKGDATADIR=""

NOPROFILE=1
NO_PROFILE=1
.include <bsd.lib.mk>
